### ISSUE TITLE
issue with react-native-material-ui import

### ISSUE THREAD

**Issue by msmuthu3** [VISI-ONE/create-react-native-web-example#1]
Thanks for creating this awesome example repo. Iam trying to invclude react-native-material-ui to facilitate cross platform development .However any import from that is throwing this error below . any config file update to be made for this ? Thanks in advance 

```
./node_modules/react-native-material-ui/src/Button/Button.react.js
Module parse failed: Unexpected token (100:6)
You may need an appropriate loader to handle this file type.
|   if (raised && !disabled) {
|     local.container = {
|       ...local.container,
|       ...getPlatformElevation(state.elevation),
|     };``
```

**Comment by orYoffe** [comment]
@msmuthu3 you should include the es6 libs in webpack configs in the babel-loader
`test: /\.(js|jsx|mjs)$/,
            include: [
              paths.appSrc,
              path.resolve('node_modules/react-native-swipe-gestures/'),
              path.resolve('node_modules/react-native-material-ui/'), //    <====  like this 
            ],
            loader: require.resolve('babel-loader'),`

**Comment by msmuthu3** [comment]
Thanks @orYoffe  !that worked 👍
