### ISSUE TITLE
Unable to compile fresh clone

### ISSUE THREAD

**Issue by jordanwallwork** [VISI-ONE/create-react-native-web-example#2]
I've cloned the repo, run `npm install`, and then attempted to run using `npm run web` but I get the following error:

	./src/index.js
	Module build failed: Error: Plugin 0 specified in "...\\node_modules\\babel-preset-react-native\\index.js" provided an invalid property of "default" (While processing preset: "...\\node_modules\\babel-preset-react-native\\index.js")
		at Array.map (<anonymous>)
		at Array.map (<anonymous>)

Is there something more I should be doing in order to get started?

**Comment by jordanwallwork** [comment]
Yes that worked, thanks! Do you know why that'd be the case? I'm not really familiar with yarn

**Comment by orYoffe** [comment]
@jordanwallwork this is not a repo to work with, it is just an example for what you could build with create-react-native-web cli => https://github.com/VISI-ONE/create-react-native-web-app
