### ISSUE TITLE
How to remove auto added classes for all html tags

### ISSUE THREAD

**Issue by theone3nu** [VISI-ONE/create-react-native-web-example#3]
I am getting these classes always on every tag View,Text, Buttons 
rn-alignItems-1oszu61.

Please find screenshot. I want to write my own css. Due to these classes i have to overwrite everything. Is there any way to remove all these classes at once.

<img width="656" alt="screen shot 2019-02-16 at 9 39 09 pm" src="https://user-images.githubusercontent.com/22262757/52902189-9f5e7780-3233-11e9-860b-5a8e46e23b14.png">

**Comment by orYoffe** [comment]
not sure this is a question for react-native-web repo https://github.com/necolas/react-native-web
